name: Deploy AWS CRC Front-end

run-name: ${{ github.actor }} has pushed changes to the Main Branch

on:
  push:
    branches:
      - main
      - 'release/**'

jobs:

  deploy_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      
      - name: Install modules
        run: 
          npm ci
      
      - name: Build application
        run: 
          npx astro build

      - name: Deploy to S3
        run: 
          aws s3 sync --delete ./dist/ s3://${{ secrets.BUCKET_ID }}
      
      - name: Create CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
  
        
  cypress_install:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cypress install
      uses: cypress-io/github-action@v6
      with:
        # Disable running of tests within install job
        runTests: false
        build: npm run build

    - name: Save build folder
      uses: actions/upload-artifact@v4
      with:
        name: build
        if-no-files-found: error
        path: build

  cypress_run:
    runs-on: ubuntu-latest
    needs: [cypress_install, deploy_job]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # - name: ⎔ Setup pnpm
      #   uses: pnpm/action-setup@v4

      - name: Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          browser: chrome