name: Deploy AWS CRC Front-end

run-name: ${{ github.actor }} has pushed changes to the Main Branch

on:
  push:
    branches:
      - main
      - 'release/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      checkout:
        - name: Checkout
          uses: actions/checkout@v4
  
      setup_credentials:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ap-southeast-1
      
      install_project_dependencies: 
      - name: Install modules
        run: npm ci
      
      build_project:
      - name: Build application
        run: npx astro build

      deploy_website:
      - name: Deploy to S3
        run: aws s3 sync --delete ./dist/ s3://${{ secrets.BUCKET_ID }}
      

      invalidate_cache:
      - name: Create CloudFront invalidation
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
      
      run_tests:
      - name: Cypress Tests
        uses: cypress-io/github-action@v6
        needs: deploy_website
        with:
          build: npm run build
          start: npm start
          browser: chrome